# Generated by Django 5.2.8 on 2025-11-18 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discounted_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('composition', models.TextField(blank=True, default='')),
                ('prodapp', models.TextField(blank=True, default='')),
                ('category', models.CharField(choices=[('AR', 'Armani'), ('AV', 'Aventus'), ('YSL', 'Yves Saint Laurent'), ('DR', 'Dior'), ('MM', 'Maison Margiela'), ('PDM', 'Parfumes De Marley')], max_length=3)),
                ('product_image', models.ImageField(upload_to='product')),
            ],
        ),
    ]
