# Generated by Django 5.2.7 on 2025-11-22 12:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('AR', 'Armani'), ('CD', 'Creed'), ('YSL', 'Yves Saint Laurent'), ('DR', 'Dior'), ('MM', 'Maison Margiela'), ('PDM', 'Parfumes De Marley'), ('VT', 'Valentino'), ('LV', 'Louis Vuitton')], max_length=3),
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('locality', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=50)),
                ('mobile', models.IntegerField(default=0)),
                ('zipcode', models.IntegerField()),
                ('state', models.CharField(choices=[('Alaminos', 'Alaminos'), ('Bay', 'Bay'), ('Biñan', 'Biñan'), ('Cabuyao', 'Cabuyao'), ('Calamba', 'Calamba'), ('Calauan', 'Calauan'), ('Cavinti', 'Cavinti'), ('Famy', 'Famy'), ('Kalayaan', 'Kalayaan'), ('Liliw', 'Liliw'), ('Los Baños', 'Los Baños'), ('Luisiana', 'Luisiana'), ('Lumban', 'Lumban'), ('Mabitac', 'Mabitac'), ('Magdalena', 'Magdalena'), ('Majayjay', 'Majayjay'), ('Nagcarlan', 'Nagcarlan'), ('Paete', 'Paete'), ('Pagsanjan', 'Pagsanjan'), ('Pakil', 'Pakil'), ('Pangil', 'Pangil'), ('Pila', 'Pila'), ('Rizal', 'Rizal'), ('San Pablo', 'San Pablo'), ('San Pedro', 'San Pedro'), ('Santa Cruz', 'Santa Cruz'), ('Santa Maria', 'Santa Maria'), ('Santa Rosa', 'Santa Rosa'), ('Siniloan', 'Siniloan'), ('Victoria', 'Victoria')], max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
