# Generated by Django 5.2.7 on 2025-11-25 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_payment_orderplaced'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderplaced',
            old_name='paymnent',
            new_name='payment',
        ),
    ]
